import '@/styles/globals.scss'
import '@/styles/post.scss'
import '@/styles/styles.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {PropsWithChildren} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lenscat Studio Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${inter.className} tw-container tw-mx-auto`}>
        <nav>
          asdf
        </nav>
        {children}
      </body>
    </html>
  )
}
